---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install:
  - gem install bundler -v 2.1.2
  - gem install diagram_comp '~> 1'
  - gem install node_comp '~> 1'
  - gem install linked_list_comp '~> 1'
